name: Akarat
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.4+5


environment:
  sdk: ^3.6.1

dependencies:
  carousel_slider: ^5.0.0
  standard_searchbar: ^2.0.0
  sliding_switch: ^1.0.0
  syncfusion_flutter_sliders: ^29.1.41
  syncfusion_flutter_charts: ^29.1.41
  syncfusion_flutter_core: ^29.1.41
  bubble_tab_indicator:
  tuna_flutter_range_slider: ^1.0.0
  smooth_page_indicator: ^1.1.0
  get: ^4.6.5
  shared_preferences: ^2.2.2
  flutter_map: ^8.1.1
  provider: ^6.1.3
  cached_network_image: ^3.2.3
  http: ^1.4.0
  shimmer: ^3.0.0
  html_unescape: ^2.0.0
  flutter_html: ^3.0.0
  google_sign_in: ^6.3.0
  dropdown_button2: ^2.3.9
  url_launcher: ^6.1.4
  flutter_phone_direct_caller: ^2.0.1
  dio: ^5.4.0
  flutter_riverpod: ^2.4.0
  crypto: ^3.0.2
  flutter_dotenv: ^5.0.2
  connectivity_plus: ^6.1.3
  intl: ^0.20.2
  google_maps_flutter: ^2.1.8
  flutter_hooks: ^0.21.2
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^8.0.0
  auto_size_text: ^3.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  rename: ^3.0.2
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/images/app-icon_new.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/apartment.png
    - assets/images/commercials.png
    - assets/images/duplex.png
    - assets/images/labour-camp.png
    - assets/images/land.png
    - assets/images/new-apartment.png
    - assets/images/offices.png
    - assets/images/penthouse.png
    - assets/images/retail.png
    - assets/images/rooms.png
    - assets/images/shop.png
    - assets/images/showroom.png
    - assets/images/studio.png
    - assets/images/townhouse.png
    - assets/images/villa.png
    - assets/images/warehouse.png
    - assets/images/not_found.png
    - assets/images/profile.png
