import 'dart:convert';

import 'package:Akarat/src/core/utils/secure_storage.dart';
import 'package:Akarat/src/screen/saved_alert_screen.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

import '../../l10n/app_localizations.dart';           // ← generated by flutter gen-l10n
import '../core/services/api_service.dart';
import '../features/property/data/models/property_type_model.dart';
import 'login.dart';

Future<String?> readToken() async {
  try {
    return await SecureStorage.getToken();
  } catch (_) {
    return null;
  }
}

class CreateAlertScreen extends StatefulWidget {
  final String initialPurpose;
  final String initialPropertyType;
  final bool isFromSavedAlerts;

  const CreateAlertScreen({
    super.key,
    required this.initialPurpose,
    required this.initialPropertyType,
    this.isFromSavedAlerts = false,
  });

  @override
  State<CreateAlertScreen> createState() => _CreateAlertScreenState();
}

class _CreateAlertScreenState extends State<CreateAlertScreen> {
  // ── Fields ────────────────────────────────────────────────────────────────
  final _formKey = GlobalKey<FormState>();
  final _nameCtrl = TextEditingController();

  late String _timePeriod;
  late String _purpose;
  late String _propertyType;
  late List<String> _timePeriods;

  PropertyTypeModel? propertyTypeModel;
  bool _submitting = false;

  // Localization access (safe after didChangeDependencies)
  AppLocalizations get l10n => AppLocalizations.of(context)!;

  // ── Lifecycle ─────────────────────────────────────────────────────────────
  @override
  void initState() {
    super.initState();

    fetchAllPropertyType();

    _purpose = widget.initialPurpose.trim();

    final raw = widget.initialPropertyType.trim();
    final rawLower = raw.toLowerCase();
    const anyMarkers = {'', 'all', 'any', 'all residential'};
    _propertyType = anyMarkers.contains(rawLower) ? '' : raw;

    // Initial name (will be refined with localized "Any" in build / on change)
    final labelType = _propertyType.isEmpty ? 'Any' : _propertyType;
    _nameCtrl.text = '$_purpose • $labelType';
  }

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();

    // Initialize localized time periods
    _timePeriods = [
      l10n.hourly,
      l10n.daily,
      l10n.weekly,
      l10n.monthly,
    ];

    // Set default value only once
    _timePeriod = _timePeriods.first;
  }

  @override
  void dispose() {
    _nameCtrl.dispose();
    super.dispose();
  }

  // ── Helpers ────────────────────────────────────────────────────────────────
  InputDecoration _dec(String hint) {
    return InputDecoration(
      hintText: hint,
      filled: true,
      fillColor: Colors.white,
      contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
      enabledBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(12),
        borderSide: const BorderSide(color: Color(0xFFE7E7E7)),
      ),
      focusedBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(12),
        borderSide: const BorderSide(color: Color(0xFFE7E7E7)),
      ),
    );
  }

  // Add these as static constants in the State class or in a separate constants file

  static const Map<String, String> _timePeriodToApi = {
    // English
    'Hourly': 'hourly',
    'Daily':  'daily',
    'Weekly': 'weekly',
    'Monthly': 'monthly',
    // Arabic (add the exact localized strings you use)
    'كل ساعة': 'hourly',
    'يومي':    'daily',
    'أسبوعي':  'weekly',
    'شهري':    'monthly',
    // Turkish (from your example)
    'Saatlik':  'hourly',
    'Günlük':   'daily',
    'Haftalık': 'weekly',
    'Aylık':    'monthly',
    // Add more languages as needed
  };

  static const Map<String, String> _propertyTypeToApi = {
    // Common known types – case insensitive prefix match still used below
    'villa': 'villa',
    'apartman': 'apartment',
    'daire': 'apartment',
    'ofis': 'office',
    'ticari': 'commercial',
    // ... add localized names if backend expects specific slugs
  };

  static const Map<String, String> _purposeToApi = {
    // English
    'rent': 'rent',
    'buy':  'buy',
    'sale': 'buy',           // normalize sale → buy
    'new projects': 'new projects',
    'commercial': 'commercial',
    // Arabic
    'إيجار': 'rent',
    'شراء': 'buy',
    // Turkish
    'Kiralık': 'rent',
    'Satılık': 'buy',
    // Add more as you support more languages
  };
  // ── Auth & Navigation ──────────────────────────────────────────────────────
  Future<String?> _requireAuth() async {
    final token = await readToken();
    if (!mounted) return null;

    if (token == null || token.isEmpty) {
      await Navigator.of(context).push(
        MaterialPageRoute(builder: (_) => const Login()),
      );
      final t2 = await readToken();
      return (t2 != null && t2.isNotEmpty) ? t2 : null;
    }
    return token;
  }

  Future<void> _openSavedAlerts() async {
    final token = await _requireAuth();
    if (token == null || !mounted) return;
    Navigator.of(context).push(
      MaterialPageRoute(builder: (_) => SavedAlertsScreen(token: token)),
    );
  }

  // ── Unique Name Logic ─────────────────────────────────────────────────────
  Future<String> _uniqueName(String base, String token) async {
    try {
      final response = await ApiService.get(
        '/saved-searches',
        headers: {'Authorization': 'Bearer $token'},
      );

      if (response.statusCode < 200 || response.statusCode >= 300) return base;

      final body = response.body.isNotEmpty ? jsonDecode(response.body) : null;
      List<dynamic> list = [];

      if (body is List) {
        list = body;
      } else if (body is Map) {
        list = body['data'] is List
            ? body['data']
            : body['saved_searches'] is List
            ? body['saved_searches']
            : [];
      }

      final existing = list
          .map((e) => ((e as Map)['alert_name'] ?? '').toString().trim().toLowerCase())
          .toSet();

      if (!existing.contains(base.trim().toLowerCase())) return base;

      for (int i = 2; i <= 50; i++) {
        final candidate = '$base ($i)';
        if (!existing.contains(candidate.toLowerCase())) return candidate;
      }
      return '${base}_${DateTime.now().millisecondsSinceEpoch}';
    } catch (_) {
      return base;
    }
  }

  // ── Save Logic ─────────────────────────────────────────────────────────────
  Future<void> _save(bool isFromSavedAlerts) async {
    if (!_formKey.currentState!.validate()) return;

    final token = await _requireAuth();
    if (token == null) return;

    setState(() => _submitting = true);

    final purposeForUi = _purpose.trim();
    final typeSlug = _mapTypeForApi(_propertyType);
    final purposeServerKey =
        '${_canonPurpose(purposeForUi)}|${typeSlug.isEmpty ? 'any' : typeSlug}';

    String alertName = _nameCtrl.text.trim();
    if (alertName.isEmpty) {
      final labelType = _propertyType.isEmpty ? l10n.propertyTypeAny : _propertyType;
      alertName = '$purposeForUi • $labelType';
    }

    alertName = await _uniqueName(alertName, token);

    final payload = <String, dynamic>{
      'alert_name': alertName,
      'time_period': _mapTimePeriodForApi(_timePeriod),
      'purpose': purposeServerKey,
      if (typeSlug.isNotEmpty) 'property_type': typeSlug,
    };

    try {
      var response = await ApiService.post(
        '/alerts',
        body: payload,
        headers: {'Authorization': 'Bearer $token'},
      );

      if (response.statusCode == 409 || response.statusCode == 422) {
        final newName = await _uniqueName('$alertName • 2', token);
        final retryPayload = Map<String, dynamic>.from(payload)
          ..['alert_name'] = newName;
        response = await ApiService.post(
          '/alerts',
          body: retryPayload,
          headers: {'Authorization': 'Bearer $token'},
        );
      }

      if (!mounted) return;

      if (response.statusCode >= 200 && response.statusCode < 300) {
        if (isFromSavedAlerts) {
          Navigator.pop(context);
          Navigator.pushReplacement(
            context,
            MaterialPageRoute(builder: (_) => SavedAlertsScreen(token: token)),
          );
        } else {
          Navigator.pop(context);
        }
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text(l10n.alertSaved)),
        );
        return;
      }

      String msg = l10n.alertSaveFailed;
      try {
        final body = jsonDecode(response.body);
        if (body['message'] != null) msg = body['message'];
      } catch (_) {}

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text(msg)),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text(l10n.networkError)),
        );
      }
    } finally {
      if (mounted) setState(() => _submitting = false);
    }
  }

  String _mapTimePeriodForApi(String period) {
    final trimmed = period.trim();
    // 1. Direct lookup (most reliable when using localized dropdown values)
    if (_timePeriodToApi.containsKey(trimmed)) {
      return _timePeriodToApi[trimmed]!;
    }
    // 2. Fallback: English substring match (for safety during development)
    final lower = trimmed.toLowerCase();
    if (lower.contains('hour') || lower == l10n.hourly.toLowerCase()) return 'hourly';
    if (lower.contains('day')  || lower == l10n.daily.toLowerCase())  return 'daily';
    if (lower.contains('week') || lower == l10n.weekly.toLowerCase()) return 'weekly';
    if (lower.contains('month')|| lower == l10n.monthly.toLowerCase()) return 'monthly';

    return 'daily'; // safe default
  }

  String _mapTypeForApi(String t) {
    final trimmed = t.trim();
    final lower = trimmed.toLowerCase();

    // 1. Direct known mapping (if property types are translated)
    if (_propertyTypeToApi.containsKey(lower)) {
      return _propertyTypeToApi[lower]!;
    }

    // 2. Keep your existing prefix logic (works well even when types are localized)
    if (lower.isEmpty || lower == 'all residential' || lower == 'any' || lower == 'all') {
      return '';
    }
    if (lower.startsWith('office') || lower.contains('ofis')) return 'office';
    if (lower.startsWith('commercial') || lower.contains('ticari')) return 'commercial';
    if (lower.startsWith('apart') || lower.contains('daire') || lower.contains('apartman')) {
      return 'apartment';
    }
    if (lower.startsWith('villa')) return 'villa';
    if (lower.startsWith('studio')) return 'studio';

    // 3. Fallback: slugify
    return lower.replaceAll(' ', '_');
  }

  String _canonPurpose(String p) {
    final trimmed = p.trim();
    final lower = trimmed.toLowerCase();

    // 1. Direct lookup from localized value
    if (_purposeToApi.containsKey(lower)) {
      return _purposeToApi[lower]!;
    }

    // 2. Keep your original flexible logic
    if (lower.contains('rent') || lower.contains('إيجار') || lower.contains('kiralık')) {
      return 'rent';
    }
    if (lower.contains('buy') || lower.contains('sale') ||
        lower.contains('شراء') || lower.contains('satılık')) {
      return 'buy';
    }
    if (lower.contains('new') || lower.contains('yeni proje')) {
      return 'new projects';
    }
    if (lower.contains('commercial') || lower.contains('ticari')) {
      return 'commercial';
    }

    // Fallback: return normalized original
    return lower.replaceAll(RegExp(r'[_\s-]+'), ' ');
  }


  Future<void> fetchAllPropertyType() async {
    try {
      final response = await ApiService.get('/property-types');
      if (response.statusCode == 200) {
        final data = jsonDecode(response.body);
        setState(() {
          propertyTypeModel = PropertyTypeModel.fromJson(data);
        });
      }
    } catch (e, stack) {
      debugPrint('Property types error: $e\n$stack');
    }
  }

  // ── UI ─────────────────────────────────────────────────────────────────────
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.white,
        elevation: 0,
        actions: [
          IconButton(
            onPressed: _openSavedAlerts,
            icon: const Icon(Icons.notifications_active_outlined, color: Colors.black),
            tooltip: l10n.savedAlerts,
          ),
        ],
      ),
      backgroundColor: Colors.white,
      body: propertyTypeModel == null
          ? const Center(child: CupertinoActivityIndicator(radius: 14))
          : SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
          child: Container(
            width: double.infinity,
            padding: const EdgeInsets.fromLTRB(20, 20, 20, 16),
            decoration: BoxDecoration(
              color: Colors.white,
              boxShadow: [
                BoxShadow(
                  color: Colors.grey.shade400,
                  blurRadius: 2,
                  spreadRadius: 2,
                  offset: const Offset(1, 1),
                )
              ],
              borderRadius: BorderRadius.circular(16),
            ),
            child: Stack(
              children: [
                Positioned(
                  right: -6,
                  top: -8,
                  child: IconButton(
                    icon: const Icon(Icons.close, color: Colors.red),
                    onPressed: () => Navigator.pop(context),
                  ),
                ),
                Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    const SizedBox(height: 4),
                    Text(
                      l10n.createAlertTitle,
                      style: const TextStyle(
                        fontSize: 22,
                        fontWeight: FontWeight.w700,
                        color: Colors.black,
                      ),
                    ),
                    const SizedBox(height: 18),
                    Form(
                      key: _formKey,
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            l10n.alertNameLabel,
                            style: const TextStyle(fontWeight: FontWeight.w600),
                          ),
                          const SizedBox(height: 6),
                          TextFormField(
                            controller: _nameCtrl,
                            decoration: _dec(l10n.alertNameHint),
                            validator: (v) => (v?.trim().isEmpty ?? true)
                                ? l10n.alertNameRequired
                                : null,
                          ),
                          const SizedBox(height: 16),

                          Text(
                            l10n.timePeriodLabel,
                            style: const TextStyle(fontWeight: FontWeight.w600),
                          ),
                          const SizedBox(height: 6),
                          DropdownButtonFormField<String>(
                            value: _timePeriod,
                            decoration: _dec(''),
                            dropdownColor: Colors.white,
                            icon: const Icon(Icons.keyboard_arrow_down),
                            items: _timePeriods
                                .map((e) => DropdownMenuItem(value: e, child: Text(e)))
                                .toList(),
                            onChanged: _submitting
                                ? null
                                : (v) => setState(() => _timePeriod = v ?? _timePeriod),
                          ),
                          const SizedBox(height: 16),

                          Text(
                            l10n.purposeLabel,
                            style: const TextStyle(fontWeight: FontWeight.w600),
                          ),
                          const SizedBox(height: 6),
                          Container(
                            width: double.infinity,
                            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
                            decoration: BoxDecoration(
                              color: Colors.white,
                              borderRadius: BorderRadius.circular(12),
                              border: Border.all(color: const Color(0xFFE7E7E7)),
                            ),
                            child: Text(
                              _purpose,
                              style: const TextStyle(fontSize: 16),
                            ),
                          ),
                          const SizedBox(height: 16),

                          Text(
                            l10n.propertyTypeLabel,
                            style: const TextStyle(fontWeight: FontWeight.w600),
                          ),
                          const SizedBox(height: 6),
                          DropdownButtonFormField<String>(
                            menuMaxHeight: 340,
                            value: _propertyType.isEmpty ? null : _propertyType,
                            decoration: _dec(l10n.propertyTypeAny),
                            hint: Text(l10n.propertyTypeAny),
                            dropdownColor: Colors.white,
                            icon: const Icon(Icons.keyboard_arrow_down),
                            items: propertyTypeModel!.data!.map((pt) {
                              return DropdownMenuItem(
                                value: pt.name ?? '',
                                child: Text(pt.name ?? ''),
                              );
                            }).toList(),
                            onChanged: _submitting
                                ? null
                                : (value) {
                              setState(() {
                                _propertyType = value ?? '';
                                final labelType = _propertyType.isEmpty
                                    ? l10n.propertyTypeAny
                                    : _propertyType;
                                _nameCtrl.text = '$_purpose • $labelType';
                              });
                            },
                          ),
                        ],
                      ),
                    ),
                    const SizedBox(height: 24),
                    Row(
                      children: [
                        Expanded(
                          child: _pillButton(
                            label: l10n.cancel,
                            onTap: _submitting ? null : () => Navigator.pop(context),
                            isPrimary: false,
                          ),
                        ),
                        const SizedBox(width: 12),
                        Expanded(
                          child: _pillButton(
                            label: _submitting ? l10n.savingAlert : l10n.saveAlert,
                            onTap: _submitting
                                ? null
                                : () async => await _save(widget.isFromSavedAlerts),
                            isPrimary: true,
                          ),
                        ),
                      ],
                    ),
                  ],
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Widget _pillButton({
    required String label,
    required VoidCallback? onTap,
    bool isPrimary = true,
  }) {
    return Material(
      color: Colors.transparent,
      child: InkWell(
        borderRadius: BorderRadius.circular(14),
        onTap: onTap,
        child: Container(
          height: 44,
          alignment: Alignment.center,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(14),
            gradient: isPrimary
                ? const LinearGradient(
              begin: Alignment.centerLeft,
              end: Alignment.centerRight,
              colors: [Color(0xFFFF6B6B), Color(0xFFFF8A8A)],
            )
                : null,
            border: isPrimary ? null : Border.all(color: Colors.grey.shade400),
            color: isPrimary ? null : Colors.white,
            boxShadow: isPrimary
                ? const [
              BoxShadow(
                color: Color(0x10000000),
                blurRadius: 8,
                offset: Offset(0, 2),
              ),
            ]
                : null,
          ),
          child: Text(
            label,
            style: TextStyle(
              color: isPrimary ? Colors.white : Colors.black87,
              fontWeight: FontWeight.w700,
            ),
          ),
        ),
      ),
    );
  }
}