import 'package:Akarat/src/features/property/presentation/bloc/enquiry_bloc.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:country_code_picker/country_code_picker.dart';


import 'firebase_options.dart';

// Core utilities
import 'package:Akarat/src/core/utils/session_manager.dart';

// Blocs
import 'package:Akarat/src/features/auth/presentation/bloc/auth_bloc.dart';
import 'package:Akarat/src/features/property/presentation/bloc/favorite_bloc.dart';
import 'package:Akarat/src/features/property/presentation/bloc/favorite_event.dart';
import 'package:Akarat/src/features/property/presentation/bloc/filter_bloc.dart';
import 'package:Akarat/src/features/property/presentation/bloc/location_picker_bloc.dart';

// Screens
import 'package:Akarat/src/screen/splash_screen.dart';
import 'package:Akarat/src/screen/home.dart';
import 'package:Akarat/src/screen/login.dart';
import 'package:Akarat/src/screen/register_screen.dart';
import 'package:Akarat/src/screen/my_account.dart';
import 'package:Akarat/src/screen/new_projects.dart';
import 'package:Akarat/src/screen/forgot_password.dart';
import 'package:Akarat/src/screen/otp_verification.dart';
import 'package:Akarat/src/screen/reset_password.dart';

// Localization - Generated by flutter gen-l10n
import 'package:flutter_localizations/flutter_localizations.dart';
import 'l10n/app_localizations.dart';

// Global keys for navigation and snackbars
final GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();
final GlobalKey<ScaffoldMessengerState> scaffoldMessengerKey =
GlobalKey<ScaffoldMessengerState>();

// Optional: Bloc observer for debugging
class AppBlocObserver extends BlocObserver {
  @override
  void onChange(BlocBase bloc, Change change) {
    super.onChange(bloc, change);
    debugPrint('🔄 Bloc Change: ${bloc.runtimeType} $change');
  }

  @override
  void onError(BlocBase bloc, Object error, StackTrace stackTrace) {
    debugPrint('❌ Bloc Error: ${bloc.runtimeType} $error');
    super.onError(bloc, error, stackTrace);
  }
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Load environment variables
  await dotenv.load(fileName: ".env");

  // Restore session early
  await SessionManager().restore();
  await SessionManager().refreshProfileFromServer();

  // Enable Bloc debugging
  Bloc.observer = AppBlocObserver();

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiBlocProvider(
      providers: [
        BlocProvider(create: (_) => AuthBloc()..add(AppStarted())),
        BlocProvider(create: (_) => FavoriteBloc()..add(LoadFavorites())),
        BlocProvider(create: (_) => FilterBloc()),
        BlocProvider(create: (_) => LocationPickerBloc()),
        BlocProvider(create: (_) => EnquiryBloc()),
      ],
      child: MaterialApp(
        title: 'Akarat',
        debugShowCheckedModeBanner: false,
        navigatorKey: navigatorKey,
        scaffoldMessengerKey: scaffoldMessengerKey,

        // Localization Setup - Clean & Recommended
        localizationsDelegates: [
          ...AppLocalizations.localizationsDelegates, // Includes Global* delegates
          AppLocalizations.delegate,
          CountryLocalizations.delegate, // For country_code_picker
        ],
        supportedLocales: AppLocalizations.supportedLocales,

        // Auto-detect device language, fallback to English
        localeResolutionCallback: (deviceLocale, supportedLocales) {
          return deviceLocale ??
              supportedLocales.first; // Safe fallback to first supported (English)
        },

        theme: ThemeData(
          useMaterial3: true,
          colorSchemeSeed: const Color(0xFFE01E26), // Your brand red
          fontFamily: 'Tajawal', // Perfect for Arabic + Latin support
          scaffoldBackgroundColor: Colors.white,
        ),

        // Initial screen
        home: const SplashScreen(),

        // Named routes
        routes: {
          '/login': (_) => const Login(),
          '/register': (_) => const RegisterScreen(),
          '/home': (_) => const Home(),
          '/my-account': (_) => const My_Account(),
          '/forgot-password': (_) => const ForgotPasswordScreen(),
          '/new-projects': (_) => const NewProjectsScreen(),
        },

        // Dynamic routes
        onGenerateRoute: (settings) {
          if (settings.name == '/verify-otp') {
            return MaterialPageRoute(
              builder: (_) => const OtpVerificationScreen(),
              settings: settings,
            );
          }

          if (settings.name == '/reset-password') {
            final args = settings.arguments as Map<String, dynamic>? ?? {};
            final email = args['email']?.toString().trim() ?? '';
            final token = args['token']?.toString().trim() ?? '';

            if (email.isEmpty || token.isEmpty) {
              return MaterialPageRoute(
                builder: (_) => const Scaffold(
                  body: Center(child: Text('Invalid password reset link')),
                ),
              );
            }

            return MaterialPageRoute(
              builder: (_) => ResetPasswordScreen(email: email, token: token),
              settings: settings,
            );
          }

          return null;
        },

        // Unknown route fallback
        onUnknownRoute: (_) => MaterialPageRoute(
          builder: (_) => const Scaffold(
            body: Center(child: Text('Page Not Found')),
          ),
        ),
      ),
    );
  }
}